//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness_weight_tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public int ActID { get; set; }
        public string ActName { get; set; }
        public string ActType { get; set; }
        public decimal ActDuration { get; set; }
        public Nullable<int> ActWeight { get; set; }
        public Nullable<int> ActReps { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
    }
}
