
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace fitness_weight_tracker.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FoodLog
{

    public int FoodLogID { get; set; }

    public string UserID { get; set; }

    public string Meal { get; set; }

    public System.DateTime FoodDate { get; set; }

    public string FoodName { get; set; }

    public Nullable<int> Calories { get; set; }

    public string FoodGroup { get; set; }

    public int MealServingSize { get; set; }

    public Nullable<int> Carbs { get; set; }

    public Nullable<int> TotalFat { get; set; }

    public Nullable<int> Protein { get; set; }

    public Nullable<int> Sodium { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

}

}
